#!/bin/bash
function PRINT_Version {
  echo "${tBOLD}${appname}${tSTD}-${major_version}.${minor_version}.${micro_version}-${patch_version} ${dev_status}"
  [ "$dev_status" == "stable" ] && echo "Release date: "$(date -d $release_date +%A\ %e\ %B\ %Y)
}
