#!/usr/bin/env bash
################################################################################
# OSINFO
#
# osinfo lists system information available to the OS.
# see `man osinfo` for details.
#
################################################################################
# Written by Arvid Norlander and Mikael Lammentausta                            #
#   --Advanced Bash Scripting Guide (ABS)                                       #
################################################################################
appname='osinfo'
major_version=0
minor_version=2
micro_version=12
patch_version=0
dev_status=beta
release_date='2006-11-xx'


