#!/usr/bin/env bash
################################################################################
# OSINFO
#
# osinfo lists system information available to the OS.
# see `man osinfo` for details.
#
################################################################################
# Written by Arvid Norlander and Mikael Lammentausta                            #
#   --Advanced Bash Scripting Guide (ABS)                                       #
################################################################################
appname='osinfo'
major_version=0
minor_version=3
micro_version=0
patch_version=rc2
dev_status=beta
release_date='2007-11-23'
# rc1 release_date='2006-12-22'


