#!/bin/bash

Module_video() {
	local moduleName="Video"
	local moduleDescription="Video components"
	module_header     "$moduleName"

	#add_attribute     'Video card'
	#add_attribute     'Video card chipset'

	print_X_info
	print_hw_info
	print_setup

	flush_values
}

	# list of known graphics drivers
	KNOWN_GPU_DRIVERS="nvidia\|nv\|fglrx\|radeon\|ati"

	print_X_info() {
		add_header         'Windowing system'

		add_attribute      'X version'
		add_values         "$(X -version 2>&1 | grep Revision)"

		#add_attribute     'Available X video overlays'
		
		add_attribute      'log file'
		add_values         "${XORG_LOG}"

		add_attribute      'log date'
		add_values         "$(ls -l ${XORG_LOG} | awk {'print $6 " " $7'})"

		add_footer
	}

	print_hw_info() {
		add_header         'Hardware'

		add_subheader      'Display adapter'
		 get_video_card_info
		 add_attribute      'Found chipset'
		 add_values         "$(get_found_chipset)"
		add_footer

		add_subheader      'Capabilities'
		 get_agp_rate
		add_footer

		add_footer
	}

	print_setup() {
		add_header         'Setup'

		# print GPU driver info
		add_subheader      'GPU driver for X11'
		 # vendor string
		 add_attribute      "Vendor"
		 add_values         "$(grep ' Module' ${XORG_LOG} | \
		                       grep ${KNOWN_GPU_DRIVERS}: | \
		                       sed 's/[^\"]*\"\([^\"]*\)\"[^.]*/\1/')"
		add_footer         'GPU driver'

		print_extensions


		add_subheader      'Errors'
		 add_attribute      'X'
		 #add_values         "$(get_xorg_errors)"
		add_footer

		add_footer
	}

	print_extensions(){
		add_subheader      'Extensions'
		#print_glx_info
		add_attribute      "GLX extension"
		add_values         "$(get_glx)"

		#print_dri
		add_attribute      'Direct rendering'
		add_values         "Enabled: $(glxinfo 2> /dev/null | grep -i 'direct rendering' | \
					awk -F: {'print $2'})"

		add_attribute      "OpenGL renderer"
		add_values         "$(get_opengl_renderer)"

		add_attribute      "Dri vendor"
		add_values         "$(get_dri_vendor)"

		add_attribute      "Drm vendor"
		add_values         "$(get_drm_vendor)"

		add_attribute      "GLX vendor"
		add_values         "$(get_glx_vendor)"

		add_attribute      "AIGLX"
		add_values         "$(get_aiglx)"
		
		add_footer         'Extensions'
	}

	function get_videodev_name () {
		echo TODO

		}

	function get_dri_vendor () {
		awk -F\" '/Module dri/{print $2}' ${XORG_LOG}
		}

	function get_opengl_renderer () {
		glxinfo 2> /dev/null | grep -i 'opengl renderer' | \
		 awk -F: {'print $NF'}
	}

	function get_drm_vendor () {
		awk -F\" '/Module drm/{print $2}' ${XORG_LOG}
		}

	function get_glx_vendor () {
		awk -F\" '/Module glx/{print $2}' ${XORG_LOG}
		}

	function get_aiglx () {
		grep ') AIGLX' ${XORG_LOG} | awk -F':' {'print $2'}
		}

	function get_glx () {
		grep ') GLX' ${XORG_LOG} | awk -F':' {'print $2'}
		}

	function get_found_chipset () {
		found_chipsets[${#found_chipsets[@]}]="$(
			grep 'Chipset [a-zA-Z0-9]* found' ${XORG_LOG} )"

		# TODO: debug with several video cards

		found_chipsets[${#found_chipsets[@]}]="$(
			sed 's/Chipset\ // ; s/\ found//' <<< found_chipsets[${#found_chipsets[@]}] )"

		echo ${found_chipsets[0]}
		}

	function get_agp_rate () {
		add_attribute "$(grep 'AGP' ${XORG_LOG} | awk -F':' {'print $2'} )"
		add_values    "$(grep 'AGP' ${XORG_LOG} | awk -F':' {'print $3'} )"
		}

	function get_xorg_errors () {
		grep '^(EE)'  ${XORG_LOG}
		}
